[env]
TERM = "xterm-256color"

[window]
startup_mode = "Maximized"
option_as_alt = "OnlyLeft"

[font]
normal = { family = "SFMono Nerd Font" }
bold = { family = "SFMono Nerd Font" }
italic = { family = "SFMono Nerd Font" }
bold_italic = { family = "SFMono Nerd Font" }
size = 14.0

[colors.primary]
background = "#282c34"
foreground = "#abb2bf"

[colors.normal]
black = "#282c34"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#abb2bf"
yellow = "#d19a66"

[colors.bright]
black = "#5c6370"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
magenta = "#c678dd"
red = "#e06c75"
white = "#ffffff"
yellow = "#d19a66"

[cursor]
style = "Beam"

[mouse]
hide_when_typing = true
