_zshenv_file="${(%):-%N}"

# Keep a large history limit even for zsh processes that skip ~/.zshrc.
export HISTSIZE=1000000
export SAVEHIST=1000000

# brew
BREWPREFIX="/opt/homebrew"
export HOMEBREW_BUNDLE_FILE="${_zshenv_file:A:h:h}/Brewfile"
if [[ -x "${BREWPREFIX}/bin/brew" ]]; then
    eval "$(${BREWPREFIX}/bin/brew shellenv zsh)"
fi
export FPATH="${BREWPREFIX}/share/zsh/site-functions:${FPATH}"

# fzf defaults
export FZF_DEFAULT_COMMAND="fd --hidden --follow --exclude .git"
export FZF_ALT_C_COMMAND="fd --type d --hidden --follow --exclude .git"
export FZF_CTRL_T_COMMAND=${FZF_DEFAULT_COMMAND}
export FZF_DEFAULT_OPTS="--cycle --layout=reverse"

# editor
if [[ -z "${NVIM}" ]]; then
    export VISUAL="nvim"
else
    export VISUAL="nvim --server ${NVIM} --remote"
fi
export EDITOR=${VISUAL}

# ruby
if [[ -d "${BREWPREFIX}/opt/ruby" ]]; then
    export GEM_HOME="${BREWPREFIX}/opt/ruby/lib/ruby/gems"
fi

source "${_zshenv_file:A:h}/path.zsh"

[[ -r "${HOME}/.zshenv.local" ]] && source "${HOME}/.zshenv.local"

unset BREWPREFIX
unset _zshenv_file
